Repository kubescape/node-agent, pull requests merged in 2023-12, with the labels that each got.

#154 Revert "add label with parent resource version"
  go.mod
  go.sum
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/networkmanager/network_neighbors.go
  pkg/networkmanager/network_neighbors_test.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/utils/utils.go
Labels: bug_fix

#156 use cronjob labels
  pkg/networkmanager/network_manager.go
  pkg/networkmanager/network_manager_test.go
  pkg/networkmanager/network_neighbors_test.go
  pkg/networkmanager/testdata/cronjob.json
  pkg/networkmanager/testdata/deployment.json
Labels: bug_fix

#159 add np tests
  .github/workflows/pr-merged.yaml
Labels: Tests

#160 update docs
  README.md
Labels: documentation

#162 skip exec events with empty path
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
Labels: release, bug_fix

#163 ignore ebpf events with empty container name
  pkg/containerwatcher/v1/container_watcher.go
Labels: release, Bug fix

#164 avoid race condition between container start and activity reporting
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/utils/utils.go
Labels: release, bug_fix

#165 Add TemplateHash label
  go.mod
  go.sum
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/relevancymanager/v1/testdata/nginx-spdx-filtered.json
  pkg/utils/utils.go
Labels: enhancement, release

#166 Bump k8s-interface to 155
  go.mod
  go.sum
  pkg/relevancymanager/v1/testdata/nginx-spdx-filtered.json
Labels: enhancement, release
