Repository kubescape/node-agent, pull requests merged in 2023-09, with the labels that each got.

#121 bump storage client
  go.mod
  go.sum
Labels: enhancement, release

#123 unittest: not creating a new filtered SBOM when reporting known files
  pkg/relevancymanager/v1/relevancy_manager_test.go
Labels: Tests

#124 Support non-default namespace
  pkg/storage/v1/storage_nocache.go
  pkg/storage/v1/storage_test.go
Labels: enhancement, release

#126 ensure no missing info before handleRelevancy
  pkg/relevancymanager/v1/relevancy_manager.go
Labels: Bug fix
