Repository kubescape/node-agent, pull requests merged in 2023-10, with the labels that each got.

#125 implement smart remediation manager
  configuration/config.json
  go.mod
  go.sum
  main.go
  pkg/applicationprofilemanager/applicationprofile_manager_interface.go
  pkg/applicationprofilemanager/applicationprofile_manager_mock.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/containerwatcher/container_watcher_interface.go
  pkg/containerwatcher/container_watcher_mock.go
  pkg/containerwatcher/v1/capabilities.go
  pkg/containerwatcher/v1/container_watcher.go
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/containerwatcher/v1/exec.go
  pkg/containerwatcher/v1/open.go
  pkg/containerwatcher/v1/open_test.go
  pkg/containerwatcher/v1/syscall.go
  pkg/relevancymanager/relevancy_manager_interface.go
  pkg/relevancymanager/relevancy_manager_mock.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/relevancymanager/v1/relevancy_manager_test.go
  pkg/sbomhandler/v1/sbomhandler.go
  pkg/sbomhandler/v1/sbomhandler_test.go
  pkg/storage/storage_interface.go
  pkg/storage/storage_mock.go
  pkg/storage/v1/storage_nocache.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: enhancement, release, Refactoring

#133 OpenSSF Scorecard
  README.md
Labels: documentation

#136 Adding project documentation aritfacts
  MAINTAINERS.md
  README.md
  SECURITY-INSIGHTS.yml
  SECURITY.md
Labels: documentation, enhancement

#137 bump k8s-interface version
  go.mod
  go.sum
Labels: enhancement, release

#140 Get namespace from config file
  main.go
  pkg/storage/v1/storage_nocache.go
  pkg/storage/v1/storage_test.go
Labels: release, Refactoring

#142 Bump utils package
  go.mod
  go.sum
Labels: enhancement, release

#143 load account id from secret
  go.mod
  go.sum
  main.go
Labels: enhancement, release
