Repository kubescape/node-agent, pull requests merged in 2023-08, with the labels that each got.

#112 use fullPath if not empty
  pkg/containerwatcher/v1/container_watcher.go
Labels: release

#113 Fix Test
  .github/workflows/pr-merged.yaml
Labels: Bug fix

#117 use utilsmetadata.LoadConfig to parse clusterData
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: Refactoring

#116 rewrite SBOM handling code
  go.mod
  go.sum
  main.go
  pkg/containerwatcher/container_watcher_mock.go
  pkg/containerwatcher/v1/container_watcher.go
  pkg/filehandler/filehandler_interface.go
  pkg/filehandler/v1/boltdb.go
  pkg/filehandler/v1/filehandler_test.go
  pkg/filehandler/v1/inmemory.go
  pkg/k8sclient/k8sclient_mock.go
  pkg/relevancymanager/relevancy_manager_interface.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/relevancymanager/v1/relevancy_manager_test.go
  pkg/relevancymanager/v1/relevancy_manager_types.go
  pkg/relevancymanager/v1/testdata/nginx-spdx-filtered.json
  pkg/sbom/sbom.go
  pkg/sbom/sbom_interface.go
  pkg/sbom/sbom_test.go
  pkg/sbom/v1/sbom_format_interface.go
  pkg/sbom/v1/sbom_spdx_storage_format.go
  pkg/sbom/v1/sbom_spdx_storage_format_test.go
  pkg/sbomhandler/sbomhandler_interface.go
  pkg/sbomhandler/testdata/nginx-spdx-format-mock.json
  pkg/sbomhandler/testdata/not-spdx-format.json
  pkg/sbomhandler/testdata/sbom-incomplete-mock.json
  pkg/sbomhandler/v1/sbomhandler.go
  pkg/sbomhandler/v1/sbomhandler_test.go
  pkg/storage/storage_interface.go
  pkg/storage/storage_mock.go
  pkg/storage/testdata/nginx-spdx-format-mock.json
  pkg/storage/v1/storage_nocache.go
  pkg/storage/v1/storage_test.go
  pkg/storageclient/storage_client.go
  pkg/storageclient/storage_client_interface.go
  pkg/storageclient/storage_client_mock.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: enhancement, release, Refactoring, Tests

#118 fix FilterSBOM forgetting files on subsequent runs
  pkg/sbomhandler/v1/sbomhandler.go
  pkg/sbomhandler/v1/sbomhandler_test.go
Labels: Bug fix

#119 bump otel deps
  go.mod
  go.sum
Labels: enhancement, release
