Repository kubescape/node-agent, pull requests merged in 2024-03, with the labels that each got.

#190 Custom exit codes
  internal/validator/validator.go
  main.go
  pkg/dnsmanager/dns_manager_test.go
  pkg/utils/errors.go
  pkg/utils/exitcodes.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#191 mark applicationprofiles as too big when they exceed max size
  go.mod
  go.sum
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/storage/storage_interface.go
  pkg/storage/storage_mock.go
  pkg/storage/v1/storage_nocache.go
  pkg/storage/v1/storage_test.go
  pkg/utils/utils.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 3

#199 wip: support ap watch
  main.go
  pkg/rulebindingmanager/cache/cache.go
  pkg/rulebindingmanager/cache/helpers.go
  pkg/ruleengine/objectcache/applicationprofilecache/applicationprofilecache.go
  pkg/ruleengine/objectcache/helpers.go
  pkg/ruleengine/types/types.go
  pkg/rulemanager/v1/rule_manager.go
  pkg/rulemanager/v1/rule_manager_mock.go
  pkg/watcher/dynamicwatcher/watch.go
  pkg/watcher/podwatcher.go/podwatch.go
  pkg/watcher/podwatcher.go/podwatcher_test.go
Labels: enhancement

#200 bump actions/checkout to v4
  .github/workflows/scorecard.yml
Labels: enhancement, Review effort [1-5]: 1

#203 Phase 3
  pkg/rulebindingmanager/cache/helpers.go
  pkg/ruleengine/objectcache/applicationactivitiescache/applicationactivitiescache.go
  pkg/ruleengine/objectcache/applicationprofilecache/applicationprofilecache.go
  pkg/ruleengine/objectcache/applicationprofilecache/applicationprofilecache_test.go
  pkg/ruleengine/objectcache/k8scache/k8scache.go
  pkg/ruleengine/objectcache/k8scache/k8scache_test.go
  pkg/ruleengine/objectcache/networkneighborscache/networkneighborscache.go
  pkg/ruleengine/objectcache/readfiles.go
  pkg/ruleengine/objectcache/testdata/collection_applicationactivities.json
  pkg/ruleengine/objectcache/testdata/collection_applicationprofiles.json
  pkg/ruleengine/objectcache/testdata/collection_deploy.json
  pkg/ruleengine/objectcache/testdata/collection_networkneighbors.json
  pkg/ruleengine/objectcache/testdata/collection_pod.json
  pkg/ruleengine/objectcache/testdata/collection_rs.json
  pkg/ruleengine/objectcache/testdata/nginx_applicationactivities.json
  pkg/ruleengine/objectcache/testdata/nginx_applicationprofiles.json
  pkg/ruleengine/objectcache/testdata/nginx_deploy.json
  pkg/ruleengine/objectcache/testdata/nginx_networkneighbors.json
  pkg/ruleengine/objectcache/testdata/nginx_pod.json
  pkg/ruleengine/objectcache/testdata/nginx_rs.json
  pkg/utils/events.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#208 Feature/role fixes
  main.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/containerwatcher/v1/container_watcher.go
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/containerwatcher/v1/open_test.go
  pkg/networkmanager/network_manager.go
  pkg/networkmanager/network_manager_test.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/relevancymanager/v1/relevancy_manager_test.go
  pkg/ruleengine/v1/helpers.go
  pkg/rulemanager/v1/rule_manager.go
  pkg/utils/events.go
  pkg/utils/utils.go
Labels: enhancement

#210 Feature/clamav
  go.mod
  go.sum
  main.go
  pkg/containerwatcher/helpers.go
  pkg/containerwatcher/v1/container_watcher.go
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/containerwatcher/v1/open_test.go
  pkg/malwaremanager/malware_manager_interface.go
  pkg/malwaremanager/malwaremanager_mock.go
  pkg/malwaremanager/utils/fileutil.go
  pkg/malwaremanager/v1/clamav/clamav.go
  pkg/malwaremanager/v1/clamav/config.go
  pkg/malwaremanager/v1/malware_manager.go
  pkg/malwaremanager/v1/malwarescanner_interface.go
  pkg/malwaremanager/v1/types/malwareresult.go
  pkg/malwarescanner/clamav/_clamav.go
  pkg/malwarescanner/clamav/_config.go
  pkg/malwarescanner/fileutil.go
  pkg/malwarescanner/k8sutil.go
  pkg/malwarescanner/overlay.go
  pkg/malwarescanner/types.go
  pkg/ruleengine/ruleengine_interface.go
  pkg/ruleengine/v1/_factory_test.go
  pkg/ruleengine/v1/failureobj.go
  pkg/ruleengine/v1/gen_rule_files.py
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0002_unexpected_file_access.go
  pkg/ruleengine/v1/r0003_unexpected_system_call.go
  pkg/ruleengine/v1/r0004_unexpected_capability_used.go
  pkg/ruleengine/v1/r0005_unexpected_domain_request.go
  pkg/ruleengine/v1/r0006_unexpected_service_account_token_access.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1001_exec_binary_not_in_base_image.go
  pkg/ruleengine/v1/r1002_load_kernel_module.go
  pkg/ruleengine/v1/r1003_malicious_ssh_connection.go
  pkg/ruleengine/v1/r1004_exec_from_mount.go
  pkg/ruleengine/v1/r1006_unshare_system_call.go
  pkg/ruleengine/v1/r1007_crypto_miners.go
  pkg/ruleengine/v1/rule.go
  pkg/rulemanager/exporters/alert_manager.go
  pkg/rulemanager/exporters/alert_manager_test.go
  pkg/rulemanager/exporters/csv_exporter.go
  pkg/rulemanager/exporters/csv_exporter_test.go
  pkg/rulemanager/exporters/exporter.go
  pkg/rulemanager/exporters/exporters_bus.go
  pkg/rulemanager/exporters/http_exporter.go
  pkg/rulemanager/exporters/http_exporter_test.go
  pkg/rulemanager/exporters/stdout_exporter.go
  pkg/rulemanager/exporters/syslog_exporter.go
  pkg/rulemanager/exporters/syslog_exporter_test.go
  pkg/rulemanager/v1/rule_manager.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2
