Repository kubescape/node-agent, pull requests merged in 2024-02, with the labels that each got.

#184 Adding image-tag to annotations
  go.mod
  go.sum
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/relevancymanager/v1/testdata/nginx-syft-filtered.json
  pkg/sbomhandler/syfthandler/syft_handler.go
  pkg/utils/utils.go
Labels: enhancement, Review effort [1-5]: 3

#186 fix failing test
  pkg/relevancymanager/v1/testdata/nginx-syft-filtered.json
Labels: release, Bug fix, Review effort [1-5]: 1

#185 improve patching for applicationprofiles
  go.mod
  go.sum
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/storage/storage_mock.go
  pkg/storage/v1/storage_nocache.go
  pkg/storage/v1/storage_test.go
  pkg/utils/utils.go
Labels: enhancement, release, Review effort [1-5]: 3

#188 bump storage for fix in mapmutex
  go.mod
  go.sum
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#187 ensure containerID on container start with backoff
  build/Dockerfile
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/relevancymanager/v1/relevancy_manager.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 2
