Repository kubescape/node-agent, pull requests merged in 2024-04, with the labels that each got.

#212 Status annotations
  main.go
  pkg/applicationprofilemanager/applicationprofile_manager_interface.go
  pkg/applicationprofilemanager/applicationprofile_manager_mock.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/containerwatcher/v1/container_watcher.go
  pkg/containerwatcher/v1/exec.go
  pkg/containerwatcher/v1/network.go
  pkg/containerwatcher/v1/open.go
  pkg/networkmanager/network_manager.go
  pkg/networkmanager/network_manager_interface.go
  pkg/networkmanager/network_manager_mock.go
  pkg/networkmanager/network_manager_test.go
  pkg/objectcache/applicationprofilecache/applicationprofilecache.go
  pkg/objectcache/k8scache/k8scache.go
  pkg/objectcache/networkneighborscache/networkneighborscache.go
  pkg/storage/v1/storage_nocache.go
  pkg/utils/utils.go
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#213 Feature/clamav
  go.mod
  go.sum
  main.go
  pkg/containerwatcher/v1/container_watcher.go
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/malwaremanager/malware_manager_interface.go
  pkg/malwaremanager/malwaremanager_mock.go
  pkg/malwaremanager/utils/fileutil.go
  pkg/malwaremanager/v1/clamav/clamav.go
  pkg/malwaremanager/v1/malware_manager.go
  pkg/malwaremanager/v1/malwarescanner_interface.go
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#219 Dropped events
  pkg/containerwatcher/v1/container_watcher.go
  pkg/containerwatcher/v1/dns.go
  pkg/containerwatcher/v1/exec.go
  pkg/containerwatcher/v1/network.go
  pkg/containerwatcher/v1/open.go
  pkg/containerwatcher/v1/randomx.go
  pkg/rulebindingmanager/cache/cache.go
  pkg/rulemanager/v1/rule_manager.go
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#220 Bugfix/containers
  pkg/containerwatcher/helpers.go
  pkg/containerwatcher/v1/container_watcher_private.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#223 Moved syscalls to application profile, stop relevancy manager for pre-running containers
  .github/workflows/pr-created.yaml
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/containerwatcher/v1/container_watcher.go
  pkg/relevancymanager/relevancy_manager_interface.go
  pkg/relevancymanager/relevancy_manager_mock.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/relevancymanager/v1/relevancy_manager_test.go
  pkg/utils/utils.go
Labels: enhancement, Review effort [1-5]: 3

#225 renamed storage_no_cache, fix NN patch
  main.go
  pkg/networkmanager/network_manager.go
  pkg/storage/v1/storage.go
  pkg/storage/v1/storage_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#226 fix units
  .github/workflows/pr-created.yaml
  internal/validator/validator.go
  internal/validator/validator_test.go
  mocks/readfiles.go
  mocks/testdata/collection_rs.json
  mocks/testdata/nginx_networkneighbors.json
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/objectcache/applicationprofilecache/applicationprofilecache.go
  pkg/objectcache/applicationprofilecache/applicationprofilecache_test.go
  pkg/objectcache/networkneighborscache/networkneighborscache_test.go
  pkg/relevancymanager/v1/relevancy_manager_test.go
  pkg/rulemanager/exporters/http_exporter_test.go
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#228 fix ossf/scorecard
  .github/workflows/scorecard.yml
Labels: enhancement, Review effort [1-5]: 1

#227 Ephemeral containers
  go.mod
  go.sum
  mocks/testdata/collection_pod.json
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/ruleengine/v1/helpers.go
  pkg/storage/storage_interface.go
  pkg/storage/storage_mock.go
  pkg/storage/v1/storage.go
  pkg/storage/v1/storage_test.go
  pkg/utils/utils.go
Labels: enhancement, Review effort [1-5]: 4

#229 watch running containers
  main.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/containerwatcher/v1/container_watcher.go
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/containerwatcher/v1/open_test.go
  pkg/networkmanager/network_manager.go
  pkg/objectcache/applicationprofilecache/applicationprofilecache.go
  pkg/objectcache/applicationprofilecache/applicationprofilecache_test.go
  pkg/objectcache/k8scache/k8scache.go
  pkg/objectcache/networkneighborscache/networkneighborscache.go
  pkg/objectcache/networkneighborscache/networkneighborscache_test.go
  pkg/objectcache/objectcache_interface.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/rulebindingmanager/cache/cache.go
  pkg/rulebindingmanager/cache/helpers.go
  pkg/rulebindingmanager/notifier.go
  pkg/rulebindingmanager/rulebindingmanager_interface.go
  pkg/rulebindingmanager/rulebindingmanager_mock.go
  pkg/rulemanager/v1/rule_manager.go
  pkg/watcher/dynamicwatcher/watch.go
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#231 Feature/new exporters
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/ebpf/gadgets/randomx/tracer/bpf/randomx.bpf.c
  pkg/ebpf/gadgets/randomx/tracer/bpf/randomx.h
  pkg/ebpf/gadgets/randomx/tracer/randomx_bpf.go
  pkg/ebpf/gadgets/randomx/tracer/randomx_bpf.o
  pkg/ebpf/gadgets/randomx/tracer/tracer.go
  pkg/ebpf/gadgets/randomx/types/types.go
  pkg/exporters/README.md
  pkg/exporters/alert_manager.go
  pkg/exporters/alert_manager_test.go
  pkg/exporters/csv_exporter.go
  pkg/exporters/csv_exporter_test.go
  pkg/exporters/exporter.go
  pkg/exporters/exporters_bus.go
  pkg/exporters/http_exporter.go
  pkg/exporters/http_exporter_test.go
  pkg/exporters/stdout_exporter.go
  pkg/exporters/stdout_exporter_test.go
  pkg/exporters/syslog_exporter.go
  pkg/exporters/syslog_exporter_test.go
  pkg/exporters/utils.go
  pkg/exporters/utils_test.go
  pkg/malwaremanager/malware_manager_interface.go
  pkg/malwaremanager/utils/fileutil.go
  pkg/malwaremanager/v1/clamav/clamav.go
  pkg/malwaremanager/v1/malware_manager.go
  pkg/malwaremanager/v1/types/malwareresult.go
  pkg/ruleengine/ruleengine_interface.go
  pkg/ruleengine/v1/failureobj.go
  pkg/ruleengine/v1/helpers.go
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0002_unexpected_file_access.go
  pkg/ruleengine/v1/r0003_unexpected_system_call.go
  pkg/ruleengine/v1/r0003_unexpected_system_call_test.go
  pkg/ruleengine/v1/r0004_unexpected_capability_used.go
  pkg/ruleengine/v1/r0005_unexpected_domain_request.go
  pkg/ruleengine/v1/r0006_unexpected_service_account_token_access.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1001_exec_binary_not_in_base_image.go
  pkg/ruleengine/v1/r1002_load_kernel_module.go
  pkg/ruleengine/v1/r1003_malicious_ssh_connection.go
  pkg/ruleengine/v1/r1004_exec_from_mount.go
  pkg/ruleengine/v1/r1006_unshare_system_call.go
  pkg/ruleengine/v1/r1007_crypto_miners.go
  pkg/rulemanager/exporters/alert_manager.go
  pkg/rulemanager/exporters/stdout_exporter.go
  pkg/rulemanager/exporters/syslog_exporter.go
  pkg/rulemanager/exporters/syslog_exporter_test.go
  pkg/rulemanager/v1/rule_manager.go
  pkg/rulemanager/v1/rule_manager_mock.go
  pkg/utils/utils.go
Labels: enhancement, bug_fix, Review effort [1-5]: 5

#232 fix NetworkNeighbors patch
  pkg/networkmanager/network_manager.go
Labels: bug_fix, Review effort [1-5]: 2

#233 fixed rule
  pkg/rulebindingmanager/cache/cache.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source_test.go
  pkg/watcher/dynamicwatcher/watch.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#234 adding ruleManager.ContainerCallback
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/rulebindingmanager/cache/cache.go
  pkg/rulebindingmanager/cache/cache_test.go
  pkg/rulemanager/v1/rule_manager.go
Labels: enhancement, Review effort [1-5]: 3

#230 ensure containers have a name in applicationprofiles patches
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/utils/utils.go
Labels: enhancement, Review effort [1-5]: 3

#235 Fixing r1000
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source_test.go
  pkg/ruleengine/v1/r1007_crypto_miners.go
Labels: Tests, bug_fix, Review effort [1-5]: 2

#236 adding tests
  pkg/rulebindingmanager/cache/cache.go
  pkg/rulebindingmanager/cache/cache_test.go
Labels: enhancement, Tests

#238 prometheus metrics refactor
  pkg/metricsmanager/prometheus/prometheus.go
Labels: enhancement, Review effort [1-5]: 2

#239 Bugfix/rules
  pkg/ruleengine/v1/factory.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source_test.go
  pkg/ruleengine/v1/r1005_fileless_execution.go
  pkg/ruleengine/v1/r1005_fileless_execution_test.go
  pkg/ruleengine/v1/r1007_crypto_miners_test.go
  pkg/ruleengine/v1/r1007_xmr_crypto_mining.go
  pkg/ruleengine/v1/r1007_xmr_crypto_mining_test.go
  pkg/ruleengine/v1/r1008_crypto_mining_domain.go
  pkg/ruleengine/v1/r1008_crypto_mining_domain_test.go
  pkg/ruleengine/v1/r1009_crypto_mining_port.go
  pkg/ruleengine/v1/r1009_crypto_mining_port_test.go
  pkg/rulemanager/v1/rule_manager.go
Labels: enhancement, Tests, bug_fix, Review effort [1-5]: 2

#241 Ignore missing syscalls
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/rulemanager/v1/rule_manager.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#243 Fixing all rules descriptions
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0002_unexpected_file_access.go
  pkg/ruleengine/v1/r0003_unexpected_system_call.go
  pkg/ruleengine/v1/r0004_unexpected_capability_used.go
  pkg/ruleengine/v1/r0005_unexpected_domain_request.go
  pkg/ruleengine/v1/r0006_unexpected_service_account_token_access.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1001_exec_binary_not_in_base_image.go
  pkg/ruleengine/v1/r1002_load_kernel_module.go
  pkg/ruleengine/v1/r1003_malicious_ssh_connection.go
  pkg/ruleengine/v1/r1004_exec_from_mount.go
  pkg/ruleengine/v1/r1005_fileless_execution.go
  pkg/ruleengine/v1/r1006_unshare_system_call.go
  pkg/ruleengine/v1/r1007_xmr_crypto_mining.go
  pkg/ruleengine/v1/r1008_crypto_mining_domain.go
  pkg/ruleengine/v1/r1009_crypto_mining_port.go
Labels: enhancement, Review effort [1-5]: 2

#246 Removing unused file and adding hardlink where possible
  pkg/containerwatcher/v1/exec.go
  pkg/malwaremanager/v1/clamav/clamav.go
  pkg/ruleengine/v1/gen_rule_files.py
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1004_exec_from_mount.go
  pkg/ruleengine/v1/r1005_fileless_execution.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#247 Ignore DNS events that do not have address resolution
  pkg/containerwatcher/v1/container_watcher.go
  pkg/dnsmanager/dns_manager.go
  pkg/networkmanager/network_manager.go
Labels: bug_fix, Review effort [1-5]: 2

#248 Bump storage pkg
  go.mod
  go.sum
  pkg/relevancymanager/v1/testdata/nginx-syft-filtered.json
Labels: enhancement, release, Review effort [1-5]: 1

#249 fixed addRunningContainers
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/containerwatcher/v1/container_watcher_private_test.go
  pkg/containerwatcher/v1/ig_k8sclient.go
  pkg/ruleengine/v1/helpers.go
  pkg/ruleengine/v1/r0002_unexpected_file_access.go
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#250 wip: ContainerReachedMaxTime
  pkg/applicationprofilemanager/applicationprofile_manager_interface.go
  pkg/applicationprofilemanager/applicationprofile_manager_mock.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/networkmanager/network_manager_interface.go
  pkg/networkmanager/network_manager_mock.go
  pkg/networkmanager/v1/network_manager.go
  pkg/networkmanager/v1/network_manager_interface.go
  pkg/networkmanager/v1/network_manager_mock.go
  pkg/networkmanager/v2/network_manager.go
  pkg/relevancymanager/relevancy_manager_interface.go
  pkg/relevancymanager/relevancy_manager_mock.go
  pkg/relevancymanager/v1/relevancy_manager.go
  pkg/utils/utils.go
Labels: enhancement, Review effort [1-5]: 4

#252 Feature/process tree
  go.mod
  go.sum
  pkg/exporters/alert_manager.go
  pkg/exporters/alert_manager_test.go
  pkg/exporters/csv_exporter.go
  pkg/exporters/csv_exporter_test.go
  pkg/exporters/http_exporter.go
  pkg/exporters/http_exporter_test.go
  pkg/exporters/stdout_exporter.go
  pkg/exporters/stdout_exporter_test.go
  pkg/exporters/syslog_exporter.go
  pkg/exporters/syslog_exporter_test.go
  pkg/malwaremanager/malware_manager_interface.go
  pkg/malwaremanager/v1/clamav/clamav.go
  pkg/malwaremanager/v1/malware_manager.go
  pkg/malwaremanager/v1/types/malwareresult.go
  pkg/ruleengine/ruleengine_interface.go
  pkg/ruleengine/v1/failureobj.go
  pkg/ruleengine/v1/helpers.go
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0002_unexpected_file_access.go
  pkg/ruleengine/v1/r0003_unexpected_system_call.go
  pkg/ruleengine/v1/r0004_unexpected_capability_used.go
  pkg/ruleengine/v1/r0005_unexpected_domain_request.go
  pkg/ruleengine/v1/r0006_unexpected_service_account_token_access.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1001_exec_binary_not_in_base_image.go
  pkg/ruleengine/v1/r1002_load_kernel_module.go
  pkg/ruleengine/v1/r1003_malicious_ssh_connection.go
  pkg/ruleengine/v1/r1004_exec_from_mount.go
  pkg/ruleengine/v1/r1005_fileless_execution.go
  pkg/ruleengine/v1/r1006_unshare_system_call.go
  pkg/ruleengine/v1/r1007_xmr_crypto_mining.go
  pkg/ruleengine/v1/r1008_crypto_mining_domain.go
  pkg/ruleengine/v1/r1009_crypto_mining_port.go
  pkg/rulemanager/v1/rule_manager.go
  pkg/utils/utils.go
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#253 Adding args check for new execs
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r1004_exec_from_mount.go
  pkg/rulemanager/v1/rule_manager.go
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#254 Adding node name and cluster to init
  pkg/exporters/http_exporter.go
  pkg/exporters/http_exporter_test.go
Labels: enhancement, Review effort [1-5]: 2

#255 Ignore networkmanagerv2
  main.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/networkmanager/v2/network_manager.go
  pkg/rulebindingmanager/cache/cache.go
  pkg/rulebindingmanager/types/v1/types.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#257 Change default MaxAlertsPerMinute
  pkg/exporters/http_exporter.go
  pkg/exporters/http_exporter_test.go
  pkg/rulebindingmanager/cache/cache.go
  pkg/rulebindingmanager/cache/cache_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#258 Cleaning isCached function
  pkg/rulemanager/v1/rule_manager.go
Labels: enhancement, Review effort [1-5]: 2

#260 Adding pod name to rules
  go.mod
  go.sum
  pkg/exporters/alert_manager.go
  pkg/exporters/alert_manager_test.go
  pkg/exporters/csv_exporter.go
  pkg/exporters/csv_exporter_test.go
  pkg/exporters/http_exporter_test.go
  pkg/exporters/syslog_exporter.go
  pkg/exporters/syslog_exporter_test.go
  pkg/malwaremanager/v1/clamav/clamav.go
  pkg/malwaremanager/v1/malware_manager.go
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0002_unexpected_file_access.go
  pkg/ruleengine/v1/r0003_unexpected_system_call.go
  pkg/ruleengine/v1/r0004_unexpected_capability_used.go
  pkg/ruleengine/v1/r0005_unexpected_domain_request.go
  pkg/ruleengine/v1/r0006_unexpected_service_account_token_access.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/ruleengine/v1/r1000_exec_from_malicious_source.go
  pkg/ruleengine/v1/r1001_exec_binary_not_in_base_image.go
  pkg/ruleengine/v1/r1002_load_kernel_module.go
  pkg/ruleengine/v1/r1003_malicious_ssh_connection.go
  pkg/ruleengine/v1/r1004_exec_from_mount.go
  pkg/ruleengine/v1/r1005_fileless_execution.go
  pkg/ruleengine/v1/r1006_unshare_system_call.go
  pkg/ruleengine/v1/r1007_xmr_crypto_mining.go
  pkg/ruleengine/v1/r1008_crypto_mining_domain.go
  pkg/ruleengine/v1/r1009_crypto_mining_port.go
  pkg/rulemanager/v1/rule_manager.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: enhancement, Review effort [1-5]: 2

#261 Adding a fix for the container name
  pkg/malwaremanager/v1/clamav/clamav.go
  pkg/malwaremanager/v1/malware_manager.go
  pkg/rulemanager/v1/rule_manager.go
Labels: bug_fix

#262 Fix return err
  pkg/networkmanager/v1/network_manager.go
  pkg/networkmanager/v2/network_manager.go
  pkg/ruleengine/v1/r0003_unexpected_system_call.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/utils/utils.go
Labels: bug_fix, Review effort [1-5]: 2

#265 Fix execs
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0005_unexpected_domain_request.go
  pkg/utils/applicationprofile.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#266 adding trimRuntimePrefix
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/networkmanager/v2/network_manager.go
  pkg/objectcache/helpers.go
  pkg/objectcache/helpers_test.go
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/storage/v1/applicationprofile.go
  pkg/storage/v1/network.go
  pkg/utils/utils.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#268 Fix nil reference in saveNetworkEvents
  pkg/networkmanager/v1/network_manager.go
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#271 fix panic
  pkg/objectcache/applicationprofilecache/applicationprofilecache.go
Labels: bug_fix, Review effort [1-5]: 2

#272 added component test, bump storage with fix for patch
  .github/workflows/component-tests.yaml
  go.mod
  go.sum
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  tests/component_test.go
  tests/resources/40-loadgenerator.yaml
  tests/resources/hipster_shop/deployments/00-adservice.yaml
  tests/resources/hipster_shop/deployments/00-currencyservice.yaml
  tests/resources/hipster_shop/deployments/00-emailservice.yaml
  tests/resources/hipster_shop/deployments/00-paymentservice.yaml
  tests/resources/hipster_shop/deployments/00-productcatalogservice.yaml
  tests/resources/hipster_shop/deployments/00-redis-cart.yaml
  tests/resources/hipster_shop/deployments/00-shippingservice.yaml
  tests/resources/hipster_shop/deployments/10-cartservice.yaml
  tests/resources/hipster_shop/deployments/10-recommendationservice.yaml
  tests/resources/hipster_shop/deployments/20-checkoutservice.yaml
  tests/resources/hipster_shop/deployments/30-frontend.yaml
  tests/resources/hipster_shop/services/adservice.yaml
  tests/resources/hipster_shop/services/cartservice.yaml
  tests/resources/hipster_shop/services/checkoutservice.yaml
  tests/resources/hipster_shop/services/currencyservice.yaml
  tests/resources/hipster_shop/services/emailservice.yaml
  tests/resources/hipster_shop/services/frontend-external.yaml
  tests/resources/hipster_shop/services/frontend.yaml
  tests/resources/hipster_shop/services/paymentservice.yaml
  tests/resources/hipster_shop/services/productcatalogservice.yaml
  tests/resources/hipster_shop/services/recommendationservice.yaml
  tests/resources/hipster_shop/services/redis-cart.yaml
  tests/resources/hipster_shop/services/shippingservice.yaml
  tests/scripts/setup-component-test-cluster.sh
  tests/testutils/k8s.go
Labels: enhancement, release, Tests, Review effort [1-5]: 3

#273 Network neighborhoods, fix DNS & network tracers enrichment, container watcher bug
  .github/workflows/component-tests.yaml
  go.mod
  go.sum
  main.go
  mocks/readfiles.go
  mocks/testdata/collection_networkneighborhood.json
  mocks/testdata/collection_networkneighbors.json
  mocks/testdata/nginx_networkneighborhood.json
  pkg/containerwatcher/v1/container_watcher.go
  pkg/containerwatcher/v1/container_watcher_private.go
  pkg/containerwatcher/v1/container_watcher_private_test.go
  pkg/containerwatcher/v1/dns.go
  pkg/containerwatcher/v1/ig_k8sclient.go
  pkg/containerwatcher/v1/network.go
  pkg/networkmanager/v1/network_manager.go
  pkg/networkmanager/v2/network_manager.go
  pkg/objectcache/networkneighborhoodcache/networkneighborhoodcache.go
  pkg/objectcache/networkneighborhoodcache/networkneighborhoodcache_test.go
  pkg/objectcache/networkneighborhoodcache_interface.go
  pkg/objectcache/networkneighborscache/networkneighborscache.go
  pkg/objectcache/networkneighborscache/networkneighborscache_test.go
  pkg/objectcache/networkneighborscache_interface.go
  pkg/objectcache/objectcache_interface.go
  pkg/objectcache/v1/objectcache.go
  pkg/objectcache/v1/objectcache_test.go
  pkg/ruleengine/v1/helpers.go
  pkg/ruleengine/v1/mock.go
  pkg/ruleengine/v1/r0001_unexpected_process_launched.go
  pkg/ruleengine/v1/r0005_unexpected_domain_request.go
  pkg/ruleengine/v1/r0005_unexpected_domain_request_test.go
  pkg/ruleengine/v1/r0007_kubernetes_client_executed.go
  pkg/rulemanager/v1/rule_manager.go
  pkg/utils/utils.go
  pkg/watcher/dynamicwatcher/watch_test.go
  tests/chart/values.yaml
  tests/component_test.go
  tests/resources/deployment-multiple-containers.yaml
  tests/testutils/alertmanager.go
  tests/testutils/k8s.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 4

#276 bump inspektor gadget
  go.mod
  go.sum
Labels: release
