Repository kubescape/node-agent, pull requests merged in 2024-01, with the labels that each got.

#167 Adding pod-template-hash label
  go.mod
  go.sum
  pkg/relevancymanager/v1/relevancy_manager.go
Labels: enhancement, release

#168 Call InstanceIDToSlug instead of GetSlug
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
Labels: enhancement, release

#169 use fixed IG version for high CPU usage and panic
  go.mod
  go.sum
  pkg/containerwatcher/v1/network.go
Labels: enhancement, Bug fix

#171 Adding workflow_dispatch to build process
  .github/workflows/pr-merged.yaml
Labels: enhancement

#173 use fixed IG version for high CPU usage and panic
  go.mod
  go.sum
  pkg/containerwatcher/v1/network.go
  pkg/relevancymanager/v1/testdata/nginx-spdx-filtered.json
  pkg/sbomhandler/syfthandler/syft_handler_test.go
  pkg/sbomhandler/syfthandler/testdata/kollector-syft-filtered.json
  pkg/storage/v1/storage_test.go
Labels: enhancement, Bug fix

#175 fix tests
  pkg/relevancymanager/v1/relevancy_manager_test.go
  pkg/relevancymanager/v1/testdata/nginx-spdx-filtered.json
  pkg/relevancymanager/v1/testdata/nginx-syft-crd.json
  pkg/relevancymanager/v1/testdata/nginx-syft-filtered.json
  pkg/sbomhandler/syfthandler/syft_handler_test.go
Labels: release, Tests

#176 Patch only changes
  pkg/dnsmanager/dns_manager.go
  pkg/networkmanager/network_manager.go
  pkg/networkmanager/network_manager_test.go
Labels: enhancement, release

#177 Fix/patch networks
  pkg/networkmanager/network_manager.go
Labels: release, Bug fix

#178 Reset run-number
  .github/workflows/pr-merged.yaml
Labels: enhancement

#179 change for build
  main.go
Labels: enhancement, release

#181 bump k8s-interface
  go.mod
  go.sum
Labels: release

#174 add patching for applicationprofiles
  go.mod
  go.sum
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/storage/storage_interface.go
  pkg/storage/storage_mock.go
  pkg/storage/v1/storage_nocache.go
  pkg/storage/v1/storage_test.go
Labels: enhancement, release

#182 use IG fork
  go.mod
  go.sum
Labels: enhancement, release, Review effort [1-5]: 2

#183 fix applicationprofile patching with multiple containers
  go.mod
  go.sum
  pkg/applicationprofilemanager/v1/applicationprofile_manager.go
  pkg/applicationprofilemanager/v1/applicationprofile_manager_test.go
  pkg/storage/storage_interface.go
  pkg/storage/storage_mock.go
  pkg/storage/v1/storage_nocache.go
  pkg/storage/v1/storage_test.go
  pkg/utils/utils.go
Labels: enhancement, Review effort [1-5]: 1
